# Generated by Django 5.0.10 on 2026-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
