# Generated by Django 5.2.12 on 2026-05-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_apikey_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'permissions': [('use_api_key', 'Can use an API key')], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
    ]
