# Generated by Django 5.0.3 on 2024-04-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtDynLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=255, verbose_name='EDL Name')),
                ('auto_url', models.CharField(max_length=255)),
                ('ip_fqdn', models.TextField(verbose_name='IP/FQDN')),
                ('acl', models.TextField(verbose_name='ACL')),
                ('policy_reference', models.TextField(verbose_name='Notes')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ext Dyn List',
                'verbose_name_plural': 'Ext Dyn Lists',
                'ordering': ['created_date', 'friendly_name'],
            },
        ),
        migrations.CreateModel(
            name='InboxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255, verbose_name='E-Mail Address')),
                ('fqdn_list', models.TextField(verbose_name='IP/FQDN')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Submission',
                'verbose_name_plural': 'API Submissions',
            },
        ),
    ]
