# Generated by Django 5.0.2 on 2026-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='extdynlists',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Groups'),
        ),
    ]
