# Generated by Django 5.0.2 on 2026-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_extdynlists_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extdynlists',
            name='auto_url',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
