# Generated by Django 5.0.2 on 2026-03-17 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_extdynlists_auto_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxentry',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AlterField(
            model_name='inboxentry',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-Mail Address'),
        ),
    ]
