# Generated by Django 5.0.2 on 2026-03-17 16:42

from django.db import migrations


def migrate_user_email_to_fk(apps, schema_editor):
    InboxEntry = apps.get_model('app', 'InboxEntry')
    CustomUser = apps.get_model('users', 'CustomUser')

    for entry in InboxEntry.objects.filter(submitted_by__isnull=True, user_email__isnull=False):
        try:
            user = CustomUser.objects.get(email=entry.user_email)
            entry.submitted_by = user
            entry.save(update_fields=['submitted_by'])
        except CustomUser.DoesNotExist:
            pass  # Orphaned entry — no matching user, leave submitted_by null


def reverse_migration(apps, schema_editor):
    InboxEntry = apps.get_model('app', 'InboxEntry')

    for entry in InboxEntry.objects.filter(submitted_by__isnull=False):
        entry.user_email = entry.submitted_by.email
        entry.save(update_fields=['user_email'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_submitted_by_to_inboxentry'),
    ]

    operations = [
        migrations.RunPython(migrate_user_email_to_fk, reverse_migration),
    ]
