# Generated by Django 5.0.2 on 2026-03-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_migrate_user_email_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxentry',
            name='user_email',
        ),
    ]
