# Generated by Django 5.0.10 on 2026-03-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_favorite_and_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Display Timezone')),
                ('timestamp_format', models.CharField(choices=[('Y-m-d H:i:s', '2026-03-17 14:30:00'), ('m/d/Y H:i:s', '03/17/2026 14:30:00'), ('d/m/Y H:i:s', '17/03/2026 14:30:00'), ('M d, Y H:i:s', 'Mar 17, 2026 14:30:00'), ('M d, Y g:i:s A', 'Mar 17, 2026 2:30:00 PM'), ('Y-m-d g:i:s A', '2026-03-17 2:30:00 PM'), ('m/d/Y g:i:s A', '03/17/2026 2:30:00 PM')], default='Y-m-d H:i:s', max_length=50, verbose_name='Timestamp Format')),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
