# Generated by Django 5.0.10 on 2026-03-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='chain_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='db_checksum',
            field=models.CharField(blank=True, max_length=64, verbose_name='DB Integrity Checksum'),
        ),
    ]
