# Generated by Django 5.0.10 on 2026-03-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_chain_hash_and_db_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='api_key_expiration_days',
            field=models.PositiveIntegerField(default=90, verbose_name='API key expiration (days, 14-365)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_edl_per_page',
            field=models.PositiveIntegerField(default=5, verbose_name='Default EDLs per page'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_log_per_page',
            field=models.PositiveIntegerField(default=25, verbose_name='Default logs per page'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='edl_preview_entries',
            field=models.PositiveIntegerField(default=3, verbose_name='EDL preview entries on index'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='log_retention_days',
            field=models.PositiveIntegerField(default=90, verbose_name='Log retention (days, max 180)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='max_edls_per_group',
            field=models.PositiveIntegerField(default=0, verbose_name='Max EDLs per group (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='max_entries_per_edl',
            field=models.PositiveIntegerField(default=0, verbose_name='Max entries per EDL (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='max_fqdns_per_submission',
            field=models.PositiveIntegerField(default=50, verbose_name='Max FQDNs per API submission'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='max_fqdns_per_update',
            field=models.PositiveIntegerField(default=50, verbose_name='Max FQDNs per API update'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='max_inbox_per_user',
            field=models.PositiveIntegerField(default=0, verbose_name='Max inbox entries per user (0=unlimited)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Session timeout (minutes)'),
        ),
    ]
