# Generated by Django 5.0.10 on 2026-03-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_app_settings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='api_key_expiration_days',
            field=models.PositiveIntegerField(default=90, verbose_name='API key expiration (days)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='default_edl_per_page',
            field=models.PositiveIntegerField(default=10, verbose_name='Default EDLs per page'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='log_retention_days',
            field=models.PositiveIntegerField(default=90, verbose_name='Log retention (days)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='max_edls_per_group',
            field=models.PositiveIntegerField(default=25, verbose_name='Max EDLs per group'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='max_entries_per_edl',
            field=models.PositiveIntegerField(default=5000, verbose_name='Max entries per EDL'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='max_inbox_per_user',
            field=models.PositiveIntegerField(default=25, verbose_name='Max inbox entries per user'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Session inactivity timeout (minutes)'),
        ),
    ]
