# Generated by Django 5.0.10 on 2026-03-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_update_appsettings_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='syslog_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable Syslog Forwarding'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='syslog_host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Syslog Host'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='syslog_port',
            field=models.PositiveIntegerField(default=514, verbose_name='Syslog Port'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='syslog_protocol',
            field=models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP')], default='udp', max_length=3, verbose_name='Syslog Protocol'),
        ),
    ]
