# Generated by Django 5.0.10 on 2026-03-17 22:01

from django.db import migrations


DEFAULTS = {
    'max_edls_per_group': 25,
    'max_entries_per_edl': 5000,
    'max_inbox_per_user': 25,
    'default_edl_per_page': 10,
    'default_log_per_page': 25,
    'edl_preview_entries': 3,
    'max_fqdns_per_submission': 50,
    'max_fqdns_per_update': 50,
    'log_retention_days': 90,
    'session_timeout_minutes': 30,
    'api_key_expiration_days': 90,
}

# Minimum allowed values — anything below this is invalid
MINIMUMS = {
    'max_edls_per_group': 1,
    'max_entries_per_edl': 100,
    'max_inbox_per_user': 5,
    'default_edl_per_page': 5,
    'default_log_per_page': 5,
    'edl_preview_entries': 1,
    'max_fqdns_per_submission': 1,
    'max_fqdns_per_update': 1,
    'log_retention_days': 1,
    'session_timeout_minutes': 5,
    'api_key_expiration_days': 14,
}


def fix_zero_and_invalid_defaults(apps, schema_editor):
    AppSettings = apps.get_model('app', 'AppSettings')
    for settings in AppSettings.objects.all():
        changed = False
        for field, default in DEFAULTS.items():
            val = getattr(settings, field)
            minimum = MINIMUMS.get(field, 1)
            if val < minimum:
                setattr(settings, field, default)
                changed = True
        if changed:
            settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_syslog_settings'),
    ]

    operations = [
        migrations.RunPython(fix_zero_and_invalid_defaults, migrations.RunPython.noop),
    ]
