# Generated by Django 5.0.10 on 2026-04-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_appsettings_edl_delete_protection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048, verbose_name='Original URL')),
                ('short_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='nginxrejection',
            new_name='app_nginxre_ip_addr_e5a2f9_idx',
            old_name='app_nginxrej_ip_addr_ts_idx',
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortened_urls', to=settings.AUTH_USER_MODEL),
        ),
    ]
