# Generated by Django 5.0.10 on 2026-04-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_shortenedurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
    ]
