# Generated by Django 5.0.10 on 2026-04-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_shortenedurl_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='timezone_configured',
            field=models.BooleanField(default=False, verbose_name='Timezone has been configured'),
        ),
    ]
