# Generated by Django 5.0.10 on 2026-04-07 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_whitelistedip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=250, verbose_name='Max file size (MB)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='resend_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Resend API Key'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='resend_from_email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='From Email Address'),
        ),
        migrations.CreateModel(
            name='OneTimeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='otf/', verbose_name='File')),
                ('original_filename', models.CharField(max_length=500, verbose_name='Original Filename')),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_hours', models.PositiveIntegerField(choices=[(1, '1 hour'), (6, '6 hours'), (12, '12 hours'), (24, '1 day'), (72, '3 days'), (168, '7 days')], default=24, verbose_name='Expires After')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('burned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One-Time File',
                'verbose_name_plural': 'One-Time Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
