# Generated by Django 5.0.10 on 2026-04-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_appsettings_max_file_size_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='otf_brand_bg_color',
            field=models.CharField(blank=True, default='#1a1d21', max_length=7, verbose_name='Brand Background Color'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='otf_brand_image',
            field=models.FileField(blank=True, upload_to='branding/', verbose_name='Brand Logo'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='otf_brand_name',
            field=models.CharField(blank=True, default='KineticLull', max_length=255, verbose_name='File Share Brand Name'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='otf_brand_text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Brand Text Color'),
        ),
    ]
