# Generated by Django 5.0.10 on 2026-04-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_appsettings_otf_brand_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='otf_brand_card_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Card Background Color'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='otf_brand_name',
            field=models.CharField(blank=True, default='KineticLull Secure File Access', max_length=255, verbose_name='File Share Brand Name'),
        ),
    ]
