# Generated by Django 5.0.10 on 2026-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_appsettings_otf_brand_card_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='otf_brand_card_text_color',
            field=models.CharField(blank=True, default='#212529', max_length=7, verbose_name='Card Text Color'),
        ),
    ]
