# Generated by Django 5.2.12 on 2026-04-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_appsettings_otf_brand_card_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='otf_brand_card_color',
            field=models.CharField(blank=True, default='#1a1d21', max_length=7, verbose_name='Card Background Color'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='otf_brand_card_text_color',
            field=models.CharField(blank=True, default='#a0a4ab', max_length=7, verbose_name='Card Text Color'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='otf_brand_text_color',
            field=models.CharField(blank=True, default='#a0a4ab', max_length=7, verbose_name='Brand Text Color'),
        ),
    ]
