# Generated by Django 5.2.12 on 2026-04-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_appsettings_otf_brand_card_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='resend_from_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='From Name'),
        ),
    ]
