# Generated by Django 5.2.12 on 2026-05-04 17:28

import app.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_encrypt_resend_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='b2_application_key',
            field=app.crypto.EncryptedCharField(blank=True, default='', max_length=512, verbose_name='B2 applicationKey'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='b2_application_key_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='B2 keyID'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='b2_bucket_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='B2 Bucket Name'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='b2_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable B2 Offsite Backup'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='b2_last_upload_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='B2 Last Upload'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='b2_last_upload_error',
            field=models.TextField(blank=True, default='', verbose_name='B2 Last Upload Error'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='b2_last_upload_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='B2 Last Uploaded File'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='b2_last_upload_status',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='B2 Last Upload Status'),
        ),
    ]
