# Generated by Django 5.2.12 on 2026-05-04 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_appsettings_robots_txt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='autoblock_long_threshold',
            field=models.PositiveIntegerField(default=30, verbose_name='Slow-Probe Threshold (cumulative hits)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='autoblock_long_window_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Slow-Probe Window (hours)'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['ip_address', 'created_at'], name='app_activit_ip_addr_02deae_idx'),
        ),
    ]
