# Generated by Django 5.2.12 on 2026-05-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_appsettings_autoblock_long_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='robots_txt',
            field=models.TextField(blank=True, default='# robots.txt for KineticLull\n# An EDL (External Dynamic List) manager for network security teams who\n# got tired of editing CSVs by hand and ssh\'ing to the firewall at 2am\n# to push a /32 block.\n#\n# Built by zeroonesix.co. Yes, that is a real TLD. No, .co is not a typo.\n#\n# ---------------------------------------------------------------------\n# Dear crawler,\n#\n# This is a private appliance. There is nothing here for you to index.\n# You have wandered into a server whose entire purpose in life is\n# blocking other servers. Read the room.\n#\n# ---------------------------------------------------------------------\n# To the human reading this in `view-source:` or `curl -s`:\n#\n# Welcome. The house rules are short:\n#\n#   - It is always DNS.\n#   - rm -rf / is not a backup strategy.\n#   - The S in IoT stands for Security.\n#   - "It works on my machine" is not a deployment plan.\n#   - Firewall rule order matters. yes, that one too.\n#   - /dev/null is the most reliable database in production.\n#   - tabs. it was always tabs.\n#   - There are 10 kinds of people: those who understand binary,\n#     those who don\'t, and those who weren\'t expecting base 3.\n#\n# ---------------------------------------------------------------------\n# To the mass scanners, bored botnets, and that one curl loop someone\n# forgot to systemctl stop in 2019:\n#\n#   - The stack you are guessing at is wrong.\n#   - Your favorites list is on file. Try harder, or try elsewhere.\n#   - The teapot is brewing. HTTP 418.\n#\n# ---------------------------------------------------------------------\n# eW91IGJhc2U2NCAtZCdkIGEgcm9ib3RzLnR4dCBlYXN0ZXIgZWdnLiB0aGF0IGlz\n# IHNvIGRlZXBseSB1bnNlcmlvdXMgdGhhdCBpIGxvdmUgaXQuIHNwb2lsZXI6IGl0\n# IHdhcyBETlMuIGl0IGlzIGFsd2F5cyBETlMuIHNheSBoaTogc2hheW5lQHplcm9v\n# bmVzaXguY28=\n#\n# no auth required,\n# don\'t sell the contents, \n# and wear your pants backwards\n# ¯\\_(ツ)_/¯\n# ---------------------------------------------------------------------\n\nUser-agent: *\nDisallow: /\n', verbose_name='robots.txt body'),
        ),
    ]
