# Generated by Django 5.2.12 on 2026-05-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_appsettings_robots_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='backup_time',
            field=models.TimeField(default='02:00', verbose_name='Daily backup time (in display timezone)'),
        ),
    ]
