# Generated by Django 5.2.12 on 2026-05-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_extdynlists_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='autoblock_custom_patterns',
            field=models.TextField(blank=True, default='', verbose_name='Custom Scanner Patterns'),
        ),
    ]
