# Generated by Django 5.2.12 on 2026-05-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_update_robots_txt_easter_egg'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='autoblock_subnet_aggregation_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable /24 Aggregation'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='autoblock_subnet_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name='Aggregation Threshold (auto-blocked /32 in same /24)'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.CharField(max_length=50, unique=True, verbose_name='IP Address or Subnet'),
        ),
    ]
