# Generated by Django 5.2.12 on 2026-05-06

from django.db import migrations


# Frozen copy of DEFAULT_ROBOTS_TXT at migration time. Inlined so future
# edits to the live constant do not retroactively change what this
# migration writes.
NEW_ROBOTS_TXT = """\
# robots.txt for KineticLull
# An EDL (External Dynamic List) manager for network security teams who
# got tired of editing CSVs by hand and ssh'ing to the firewall at 2am
# to push a /32 block.
#
# Built by zeroonesix.co. Yes, that is a real TLD. No, .co is not a typo.
#
# ---------------------------------------------------------------------
# Dear crawler,
#
# This is a private appliance. There is nothing here for you to index.
# You have wandered into a server whose entire purpose in life is
# blocking other servers. Read the room.
#
# ---------------------------------------------------------------------
# To the human reading this in `view-source:` or `curl -s`:
#
# Welcome. The house rules are short:
#
#   - It is always DNS.
#   - rm -rf / is not a backup strategy.
#   - The S in IoT stands for Security.
#   - "It works on my machine" is not a deployment plan.
#   - Firewall rule order matters. yes, that one too.
#   - /dev/null is the most reliable database in production.
#   - tabs. it was always tabs.
#   - There are 10 kinds of people: those who understand binary,
#     those who don't, and those who weren't expecting base 3.
#
# ---------------------------------------------------------------------
# To the mass scanners, bored botnets, and that one curl loop someone
# forgot to systemctl stop in 2019:
#
#   - The stack you are guessing at is wrong.
#   - Your favorites list is on file. Try harder, or try elsewhere.
#   - The teapot is brewing. HTTP 418.
#
# ---------------------------------------------------------------------
# NDg2NTc5MmMyMDQ5MjA3MzY1NjUyMDc5NmY3NTJj
# MjA2MTZlNjQyMDc5NmY3NTIwNmU2Zjc3MjA3MzY1
# CjY1MjA2ZDY1MmMyMDczNmYyMDY0NzI2ZjcwMjA2
# MTIwNmU2Zjc0NjUyMDc3NmY3NTZjNjQyMDc5NjEz
# ZgoyMDIwMmQzZDIwNzM2ODYxNzk2ZTY1NDA3YTY1
# NzI2ZjZmNmU2NTczNjk3ODJlNjM2ZjIwM2QyZDIw
# MjAK
#
# no auth required,
# don't sell the contents,
# and wear your pants backwards
# ¯\\_(ツ)_/¯
# ---------------------------------------------------------------------

User-agent: *
Disallow: /
"""


def overwrite_robots_txt(apps, schema_editor):
    AppSettings = apps.get_model('app', 'AppSettings')
    AppSettings.objects.update(robots_txt=NEW_ROBOTS_TXT)


def noop_reverse(apps, schema_editor):
    # Reversing this would clobber the operator's current robots.txt with
    # an arbitrary prior version, so do nothing on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_db_default_for_added_columns'),
    ]

    operations = [
        migrations.RunPython(overwrite_robots_txt, noop_reverse),
    ]
