# Generated by Django 5.2.14 on 2026-05-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_update_robots_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='robots_txt',
            field=models.TextField(blank=True, default='', verbose_name='robots.txt body'),
        ),
    ]
