# Generated by Django 5.2.14 on 2026-05-29 14:19

import app.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_otf_sharing_modes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('secret_text', app.crypto.EncryptedTextField(blank=True, default='', verbose_name='Secret')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('send_email', models.BooleanField(db_default=True, default=True)),
                ('expiry_hours', models.PositiveIntegerField(choices=[(1, '1 hour'), (6, '6 hours'), (12, '12 hours'), (24, '1 day'), (72, '3 days'), (168, '7 days')], default=24, verbose_name='Expires After')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('revealed', models.BooleanField(default=False)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('burned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One-Time Secret',
                'verbose_name_plural': 'One-Time Secrets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTSRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('revealed', models.BooleanField(default=False)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('burned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='app.onetimesecret')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('secret', 'email')},
            },
        ),
        migrations.CreateModel(
            name='OTSAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='app.onetimesecret')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesses', to='app.otsrecipient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
