# Generated by Django 5.2.14 on 2026-05-29 15:10

import app.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_onetimesecret_otsrecipient_otsaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('body', app.crypto.EncryptedTextField(verbose_name='Content')),
                ('language', models.CharField(blank=True, default='auto', max_length=32, verbose_name='Language')),
                ('code', models.CharField(blank=True, max_length=64, unique=True)),
                ('expiry_hours', models.PositiveIntegerField(choices=[(0, 'Never'), (1, '1 hour'), (6, '6 hours'), (12, '12 hours'), (24, '1 day'), (72, '3 days'), (168, '7 days')], default=0, verbose_name='Expires After')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paste',
                'verbose_name_plural': 'Pastes',
                'ordering': ['-created_at'],
            },
        ),
    ]
