# Generated by Django 5.2.16 on 2026-07-13 21:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_paste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.CharField(max_length=2048, validators=[app.models.validate_short_link], verbose_name='Original URL'),
        ),
    ]
